### ISSUE TITLE
Embedded Videos

### ISSUE THREAD

**Issue by moriel5** [TeamPiped/Piped-Redirects#1]
This is great to see!

Unfortunately, video embeds only show up as black boxes, though the frames do load, and right clicking them and opening the selected frame in a new tab works as expected.

**Comment by FireMasterK** [comment]
A new version has been uploaded on Firefox that should fix this!

**Comment by moriel5** [comment]
I can verify that this has certainly been fixed, at least on Neowin (where I had tested this).
