### ISSUE TITLE
Some UI Glitches to be Fixed

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped-Redirects#10]
1. When the Extension is replacing any YouTube Video embedded in any Webpage, It loads Some Components of the Site within the Frame and then Loads the Video. As a reference and Explain to this I have attached a Video Clip below.

https://user-images.githubusercontent.com/87981739/137884575-8bba9986-a2c5-484b-8fe0-8955768c0804.mp4

2. In my RSS Feed Reader, If I do Play any YouTube shorts Video. The Shorts Video is not in the `<iframe>` Correctly instead to see the Video Correctly I need to scroll it down and Choose the Full Screen Option. A video Clip is attached for this case as well.

https://user-images.githubusercontent.com/87981739/137884792-435d4a6a-35dc-473c-a582-33beb2c496ac.mp4

Is there any way that these can be fixed ?

**Comment by FireMasterK** [comment]
I don't see your first video as a problem, it's expected since Piped is quite a large web app.

**Comment by ghost** [comment]
Okay, I get the Point, But It should be fixed for Shorts Video.

**Comment by ghost** [comment]
@FireMasterK Is it possible to make the Video not to AutoPlay in the replaced embed instead I would like to use Click to Play. You can see in Video 2 that it is Playing Automatically. 

Is there a way to fix it ?

**Comment by Loki-L1130** [comment]
@FireMasterK, [Invidition](https://addons.mozilla.org/en-US/firefox/addon/invidition/) for invidious like Piped-Redirects. It does a great Job in replacing Shorts Video currenlty in iframe instead of like in the 2nd Video above. I think you can fork from it to do so.

**Comment by ghost** [comment]
FireMasterK, Are there any updates to fix the issue with shorts video ?

While using Invidious with Privacy Redirect Extension, it does replace short video just within the frame but not like Piped does. I think you need make a line of code so that any Video that plays in that fixed Window Scale within the iframe.

**Comment by Loki-L1130** [comment]
FireMasterK, Are there any updates to fix the issue with shorts video ?
