### ISSUE TITLE
[Feature Request] Option to view video in Piped site

### ISSUE THREAD

**Issue by den7007** [TeamPiped/Piped-Redirects#4]
Hi, first of all many thanks for the app, was hoping it would be integrated with Privacy Redirect add on but this works great.

Just wondering if there could be an option to view a video in the Piped page, maybe via the 3 dot menu in the corner?

Sometimes when viewing the embedded video, I would want to open it via Piped page to view the comments, but there is no way to copy the video link or click on an option that would open it in the Piped website on a new tab. YouTube videos allow you to click the YouTube button/logo so that it can open in the YouTube page.

**Comment by ghost** [comment]
I think that this is something with ShakaPlayer, The Video Player used by Piped.
